=== DimaHudovec/Training/chapter14/xmlparsin/data/airplanes.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="airplanes"
        xmlns:tns="airplanes"
        elementFormDefault="qualified">
  <complexType name="Airplane">
    <sequence>
      <element name="price" type="double" />
      <element name="radar" type="boolean" />
      <element name="parameters" type="tns:Parameters" />
    </sequence>
    <attribute name="model" type="string" use="required" />
    <attribute name="origin" type="string" use="required" />
  </complexType>
  <complexType name="Parameters">
    <sequence>
      <element name="lengt" type="positiveInteger" />
      <element name="width" type="positiveInteger" />
      <element name="heigh" type="positiveInteger" />
    </sequence>
  </complexType>
  <complexType name="CargoAirplane">
    <complexContent>
      <extension base="tns:Airplane">
        <sequence>
          <element name="carigecapacity" type="positiveInteger" />
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="PassengerAirplane">
    <complexContent>
      <extension base="tns:Airplane">
        <sequence>
          <element name="capacity" type="positiveInteger" />
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="airplane" type="tns:Airplane" abstract="true"></element>
  <element name="cargoairplane" type="tns:CargoAirplane" substitutionGroup="tns:airplane"></element>
  <element name="passengerairplane" type="tns:PassengerAirplane" substitutionGroup="tns:airplane"></element>

  <element name="airplanes">
    <complexType>
      <sequence>
        <element ref="tns:airplane" minOccurs="1" maxOccurs="unbounded" />
      </sequence>
    </complexType>
  </element>
</schema>

=== DimaHudovec/Training/chapter14/xmlparsin/data/airplanes.xml
<?xml version="1.0" encoding="UTF-8"?>
<airplanes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="airplanes"
           xsi:schemaLocation="airplanes airplanes.xsd">
    <cargoairplane model="AN" origin="Russia">
        <price>150</price>
        <radar>true</radar>
        <parameters>
            <lengt>35</lengt>
            <width>16</width>
            <heigh>12</heigh>
        </parameters>
        <carigecapacity>125</carigecapacity>
    </cargoairplane>
    <passengerairplane model="Boing" origin="USA">
        <price>400</price>
        <radar>true</radar>
        <parameters>
            <lengt>100</lengt>
            <width>30</width>
            <heigh>25</heigh>
        </parameters>
        <capacity>225</capacity>
    </passengerairplane>
</airplanes>
